# These categories will be applied to all DAGs in the repo.
categories:
  - ETL/ELT
  - Orchestration
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/airflow-azure-data-factory.py